### ISSUE TITLE
Niveles de materia y los niveles de las preguntas generan caída del programa

### ISSUE THREAD

**Issue by vicbguti-espol** [vicbguti-espol/POO-P3-G07#26]
El programa necesita ser robusto cuando los niveles de una materia no van acorde a las preguntas que tiene la materia.

Por ejemplo, el programa se puede caer en este caso
| Materia | Niveles de la materia | Niveles de las preguntas |
|---------|-----------------------|--------------------------|
| POO     | 3                     | 2,3                      |

Se cae porque solo hay 2 niveles en lugar de 3

Solución: Trabajar en evitar que suceda esto, mediante esconder las materias o niveles cuando sucede esto en NuevoJuegoController

**Comment by vicbguti29** [comment]
Hola Víctor, no atendemos requerimientos. Pasamos la materia
